### ISSUE TITLE
panic: agent tsnet server is not running

### ISSUE THREAD

**Issue by lucasfcnunes** [loft-sh/vcluster#2212]
### What happened?

```jsonl
syncer {"level":"error","ts":1728424782.3093603,"caller":"filters/wrap.go:54","msg":"timeout or abort while handling: method=GET URI=\"/v1-k3s/connect\" audit-ID=\"0e22dc61-7326-41bd-b5b2-2118554cee6f\"","component":"vcluster"}
syncer {"level":"info","ts":1728424808.669536,"caller":"commandwriter/commandwriter.go:126","msg":"Failed to get storage metrics","component":"vcluster","component":"k3s","location":"metrics.go:299","storage_cluster_id":"etcd-0","err":"rpc error: code = Unknown desc = sql: Scan error on column index 0, name \"SUM(data_length + index_length)\": converting driver.Value type []uint8 (\"2.5803878052e+10\") to a int64: invalid syntax"}
syncer {"level":"info","ts":1728424838.662725,"caller":"commandwriter/commandwriter.go:126","msg":"Failed to get storage metrics","component":"vcluster","component":"k3s","location":"metrics.go:299","storage_cluster_id":"etcd-0","err":"rpc error: code = Unknown desc = sql: Scan error on column index 0, name \"SUM(data_length + index_length)\": converting driver.Value type []uint8 (\"2.6911196616e+10\") to a int64: invalid syntax"}
syncer panic: agent tsnet server is not running
syncer 
syncer goroutine 471 [running]:
syncer github.com/loft-sh/vcluster-pro/pkg/tailscale.ConnectToPlatform.func3()
syncer     github.com/loft-sh/vcluster-pro/pkg/tailscale/tsnet.go:190 +0x3ce
syncer created by github.com/loft-sh/vcluster-pro/pkg/tailscale.ConnectToPlatform in goroutine 1
syncer     github.com/loft-sh/vcluster-pro/pkg/tailscale/tsnet.go:178 +0xeff
Stream closed EOF for vcluster/vcluster-dev-74dd669c89-p67b9 (syncer)
```

### What did you expect to happen?

No panic.

### How can we reproduce it (as minimally and precisely as possible)?

Don't know

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.30.3-gke.1969001
```

</details>

### vcluster version

<details>

```console
$ vcluster --version
vcluster version 0.20.1
```

</details>

### VCluster Config

<details>

```
# My vcluster.yaml / values.yaml here
```

</details>

**Comment by FabianKramm** [comment]
@lucasfcnunes thanks for creating this issue! Can you run a `kubectl delete secret vcluster-platform-api-key -n VCLUSTER_NAMESPACE` and then restart the vCluster? It seems that this is caused by general networking issues, are you running in a special environment?
