### ISSUE TITLE
Panic with latest alpha release

### ISSUE THREAD

**Issue by efrecon** [loft-sh/vcluster#31]
The latest `0.3.0-alpha.0` release of the `vcluster` CLI will panic with the following stack when run (even when requesting for help, e.g. `vcluster help`):

```
panic: create flag redefined: release-values

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc00028a400, 0xc000428d20)
        /Users/runner/work/vcluster/vcluster/vendor/github.com/spf13/pflag/flag.go:848 +0x825
github.com/spf13/pflag.(*FlagSet).VarPF(0xc00028a400, 0x1835300, 0xc0004289a8, 0x1663e03, 0xe, 0x0, 0x0, 0x16a89dd, 0x3f, 0xc000428c80)
        /Users/runner/work/vcluster/vcluster/vendor/github.com/spf13/pflag/flag.go:831 +0x10b
github.com/spf13/pflag.(*FlagSet).VarP(...)
        /Users/runner/work/vcluster/vcluster/vendor/github.com/spf13/pflag/flag.go:837
github.com/spf13/pflag.(*FlagSet).StringVar(0xc00028a400, 0xc0004289a8, 0x1663e03, 0xe, 0x0, 0x0, 0x16a89dd, 0x3f)
        /Users/runner/work/vcluster/vcluster/vendor/github.com/spf13/pflag/string.go:37 +0x9b
github.com/loft-sh/vcluster/cmd/vclusterctl/cmd.NewCreateCmd(0xc0003cdb48, 0xc000189ef0)
        /Users/runner/work/vcluster/vcluster/cmd/vclusterctl/cmd/create.go:108 +0x3c7
github.com/loft-sh/vcluster/cmd/vclusterctl/cmd.BuildRoot(0x185ab58, 0x2106ec0, 0xe)
        /Users/runner/work/vcluster/vcluster/cmd/vclusterctl/cmd/root.go:57 +0xfe
github.com/loft-sh/vcluster/cmd/vclusterctl/cmd.Execute()
        /Users/runner/work/vcluster/vcluster/cmd/vclusterctl/cmd/root.go:33 +0x47
main.main()
        /Users/runner/work/vcluster/vcluster/cmd/vclusterctl/main.go:16 +0x3e
```

**Comment by efrecon** [comment]
I see now that you are already fixing it with #30. Would you mind making a new alpha with the fix?

**Comment by FabianKramm** [comment]
@efrecon thanks for opening this issue! Yes this will be fixed with #30, I'll create a new release right now

**Comment by efrecon** [comment]
Perfect! Thanks! It just built to https://github.com/users/efrecon/packages/container/vcluster/2745339?tag=v0.3.0-alpha.1. Should also arrive at the Docker Hub soon, but automated builds there are much slower...

**Comment by FabianKramm** [comment]
@efrecon it should be available now, however you will need to specify the new version via `vcluster create ... --chart-version v0.3.0-alpha.1` with the new cli as it will deploy the latest (v0.2.0) otherwise
