### ISSUE TITLE
vcluster v0.8.0 fails to start when using v1.20 and earlier version of virtual kubernetes

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster#474]
### What happened?

vcluster syncer fails to start due to the missing kind "EndpointSlice" in version "discovery.k8s.io/v1"
```
E0511 12:07:34.185231       1 logr.go:265] controller-runtime: source: if kind is a CRD, it should be installed before calling Start no matches for kind "EndpointSlice" in version "discovery.k8s.io/v1" kind schema.GroupKind{Group:"discovery.k8s.io", Kind:"EndpointSlice"}
E0511 12:07:44.172864       1 controller.go:203] reconciler group  reconciler kind Endpoints: controller: kubernetes_default_endpoint: Could not wait for Cache to sync failed to wait for kubernetes_default_endpoint caches to sync: timed out waiting for cache to be synced
I0511 12:07:44.173081       1 logr.go:249] Stopping and waiting for non leader election runnables
I0511 12:07:44.173101       1 logr.go:249] Stopping and waiting for leader election runnables
I0511 12:07:44.173197       1 controller.go:240] reconciler group  reconciler kind ConfigMap: controller: init_manifests: Shutdown signal received, waiting for all workers to finish
I0511 12:07:44.173272       1 controller.go:242] reconciler group  reconciler kind ConfigMap: controller: init_manifests: All workers finished
I0511 12:07:44.173290       1 logr.go:249] Stopping and waiting for caches
I0511 12:07:44.177981       1 logr.go:249] Stopping and waiting for webhooks
I0511 12:07:44.177999       1 logr.go:249] Wait completed, proceeding to shutdown the manager
panic: failed to wait for kubernetes_default_endpoint caches to sync: timed out waiting for cache to be synced

goroutine 634 [running]:
github.com/loft-sh/vcluster/cmd/vcluster/cmd.startControllers.func2()
	/vcluster-dev/cmd/vcluster/cmd/start.go:393 +0x4b
created by github.com/loft-sh/vcluster/cmd/vcluster/cmd.startControllers
	/vcluster-dev/cmd/vcluster/cmd/start.go:390 +0x1b6
```

### What did you expect to happen?

vcluster should successfully start and it's pod should report the Ready state

### How can we reproduce it (as minimally and precisely as possible)?

get vcluster cli version 0.8.0 and create a cluster using these values:
```
vcluster:
  image: rancher/k3s:v1.20.15-k3s1 
```

### Anything else we need to know?

"EndpointSlice" in version "discovery.k8s.io/v1" has been introduced in Kubernetes v1.21.
Prior to that "EndpointSlice" in version "discovery.k8s.io/v1beta1" has been available ([since v1.16](https://github.com/kubernetes/kubernetes/blob/c50579afb1c3fbb2b83007bba6e8d285436d5dc9/staging/src/k8s.io/api/discovery/v1beta1/types.go#L26-L34)).

The vcluster `k8sdefaultendpoint` controller is using EndpointSlices. It should fall back to version "discovery.k8s.io/v1beta1" when "discovery.k8s.io/v1" EndpointSlice is not available in the virtual cluster API server.
Some inspiration can be drawn from how the Ingress controller falls back to older version - https://github.com/loft-sh/vcluster/blob/main/pkg/controllers/resources/ingresses/register.go 

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"07959215dd83b4ae6317b33c824f845abd578642", GitTreeState:"clean", BuildDate:"2022-03-30T18:28:25Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>

### vlcuster version

<details>
0.8.0
</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>
applicable to all distributions
</details>

### OS and Arch

<details>
N/A
</details>

**Comment by Shaked** [comment]
Thank you @matskiv I will start asap and keep you posted!

**Comment by nrchakradhar** [comment]
Not directly related to this, but wanted to know if there is any version matrix maintained that shows which versions of vcluster are compatible with which versions of host kubernetes?

**Comment by nrchakradhar** [comment]
Thanks for the information @FabianKramm
